#!/bin/bash

# This bash script generates the pygments LaTeX style definitions for a
# given pygments style

if [ "$#" -lt 1 ] ; then
        echo "Usage: createPreamble <<pygmentStyleName>>"
        exit 1
fi

styleName=$1
dirPath=lpil

echo ""
echo Creating the pygments LaTeX style file for $styleName
echo in the directory $dirPath
echo ""

cd $dirPath
echo % Pygments style: $styleName                 > lpil${styleName}Pygments.sty
echo \\ProvidesPackage{lpil${styleName}Pygments} >> lpil${styleName}Pygments.sty
pygmentize -f latex -S $styleName -a .syntax     >> lpil${styleName}Pygments.sty

echo ""
