#!/bin/bash

# This script updates the current LPiL-LaTeX package into the local
# TEXMFLOCAL

# As for the TEXMFLOCAL value from the TeXLive Manager (tlmrg)
TEXMFLOCAL=`tlmgr conf | grep TEXMFLOCAL | cut -d= -f2`

# Copy the current version over to the local TEXMFLOCAL directory
cp -R lpil $TEXMFLOCAL/tex/latex

# Now we need to update TeXLive's file search database
mktexlsr
