#!/bin/bash

# This script updates the current LPiL-TeX packages into the local
# TEXMFLOCAL

# Ask for the TEXMFLOCAL value from the TeXLive Manager (tlmrg)
TEXMFLOCAL=`tlmgr conf | grep TEXMFLOCAL | cut -d= -f2`

######################################################################
# LaTeX
# Copy the current LaTeX version over to the local TEXMFLOCAL directory
mkdir -p $TEXMFLOCAL/tex/latex
cp -R lpil $TEXMFLOCAL/tex/latex

# Now we need to update TeXLive's file search database
mktexlsr
